# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Code references

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  scan-repo:
    runs-on: ubuntu-latest
    name: Scan repository for code references
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Scan & upload
      uses: configcat/scan-repository@v1
      with:
        api-user: ${{ secrets.CONFIGCAT_API_USER }}
        api-pass: ${{ secrets.CONFIGCAT_API_PASS }}
        config-id: 08d9b0bd-07d4-4201-8553-69797f899896
